package at.ac.fhcampuswien.fhmdb.models;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.List;

//Movie data required for the database
@DatabaseTable(tableName = "movie")
public class MovieEntity {
    //Field: attribute in the table
    //generateID: automatic display of the id for new entries
    @DatabaseField(generatedId = true)
    private long id;
    @DatabaseField()
    private String apild, title, description, genres, imgUrl;
    @DatabaseField()
    private int releaseYear, lengthInMinutes;
    @DatabaseField()
    private double rating;

    public MovieEntity(){
    }

    //Without id (generated by database)
    public MovieEntity(String apild, String title, String description, String genres, String imgUrl, int releaseYear, int lengthInMinutes, double rating) {
        this.apild = apild;
        this.title = title;
        this.description = description;
        this.genres = genres;
        this.imgUrl = imgUrl;
        this.releaseYear = releaseYear;
        this.lengthInMinutes = lengthInMinutes;
        this.rating = rating;
    }

    //Constructor for WatchlistMovieEntity Subclass
    public MovieEntity(String title, String description, String genres, String imgUrl, int releaseYear, int lengthInMinutes, double rating) {
        this.title = title;
        this.description = description;
        this.genres = genres;
        this.imgUrl = imgUrl;
        this.releaseYear = releaseYear;
        this.lengthInMinutes = lengthInMinutes;
        this.rating = rating;
    }
    public String movieToString(){
        return this.title + this.description + this.genres + this.imgUrl + this.releaseYear + this.lengthInMinutes + this.rating;
    }
}
