package at.ac.fhcampuswien.fhmdb.models;

//Contains links to the movies in the watchlist, e.g. the ApiId of the selected MovieEntities
public class WatchlistMovieEntity extends MovieEntity{
    private long id;
    private String apild;

    public WatchlistMovieEntity(){
    }

    //Without id (generated by database)
    public WatchlistMovieEntity(String apild, String title, String description, String genres, String imgUrl, int releaseYear, int lengthInMinutes, double rating) {
        super(title, description, genres, imgUrl, releaseYear, lengthInMinutes, rating);
        this.apild = apild;
    }


}
